### ISSUE TITLE
右上角提示正在下载弹幕文件，鼠标移动上去显示网络错误

### ISSUE THREAD

**Issue by sushadangchu** [xmcp/pakku.js#108]
网络错误

CID = 111255404

Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://api.bilibili.com/x/v1/dm/list.so?oid=111255404&pakku_request'.

Error: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://api.bilibili.com/x/v1/dm/list.so?oid=111255404&pakku_request'.
    at down_danmaku (chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/all_core.js:1484:13)
    at onbeforerequest (chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/all_core.js:1701:60)
    at subEventCallback (extensions::webRequestEvent:81:32)

<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 9.2.6

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36`

**Incognito:** `false`

**localStorage:** `{"MARK_THRESHOLD":"1","DANMU_MARK":"suffix","TAOLUS":"","FOOLBAR":"off","BLACKLIST":"[]","_LAST_UPDATE_TIME":"1554035737686","FLASH_NOTIF":"on","_ADVANCED_USER":"on","SHRINK":"off","TRIM_SPACE":"on","MAX_DIST":"5","TRIM_ENDING":"on","AUTO_DANMU_LIST":"off","MAX_COSINE":"60","REMOVE_SEEK":"off","POPUP_BADGE":"percent","WHITELIST":"[]","FLUCTLIGHT":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","CLOUD_SYNC":"on","PROC_TYPE7":"on","THRESHOLD":"20","TRIM_WIDTH":"on","PROC_POOL1":"off","CROSS_MODE":"on","HIDE_THRESHOLD":"0","BREAK_UPDATE":"off","DANMU_SUBSCRIPT":"off","PROC_TYPE4":"on","TRIM_PINYIN":"on","ENLARGE":"off","AUTO_DISABLE_DANMU":"off","MODE_ELEVATION":"on","TOOLTIP":"on","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200"}`

**Views:**

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/background.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/options.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.html`

**Background / IS_FIREFOX:** false

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{"30":{"error":"网络错误","cid":"110896857","details":"Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://api.bilibili.com/x/v1/dm/list.so?oid=110896857&pakku_request'.\n\nError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://api.bilibili.com/x/v1/dm/list.so?oid=110896857&pakku_request'.\n    at down_danmaku (chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/all_core.js:1484:13)\n    at onbeforerequest (chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/all_core.js:1701:60)\n    at subEventCallback (extensions::webRequestEvent:81:32)"},"34":{"error":"网络错误","cid":"111255404","details":"Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://api.bilibili.com/x/v1/dm/list.so?oid=111255404&pakku_request'.\n\nError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://api.bilibili.com/x/v1/dm/list.so?oid=111255404&pakku_request'.\n    at down_danmaku (chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/all_core.js:1484:13)\n    at onbeforerequest (chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/all_core.js:1701:60)\n    at subEventCallback (extensions::webRequestEvent:81:32)"}}`

**Storage / Sync:** {"AUTO_DANMU_LIST":"off","AUTO_DISABLE_DANMU":"off","AUTO_PREVENT_SHADE":"off","BLACKLIST":"[]","BREAK_UPDATE":"off","CLOUD_SYNC":"on","CROSS_MODE":"on","DANMU_MARK":"suffix","DANMU_SUBSCRIPT":"off","ENLARGE":"off","FLASH_NOTIF":"on","FLUCTLIGHT":"off","FOOLBAR":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"1","MAX_COSINE":"60","MAX_DIST":"5","MODE_ELEVATION":"on","POPUP_BADGE":"percent","PROC_POOL1":"off","PROC_TYPE4":"on","PROC_TYPE7":"on","REMOVE_SEEK":"off","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200","SHRINK":"off","THRESHOLD":"20","TOOLTIP":"on","TRIM_ENDING":"on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"on","_LAST_UPDATE_TIME":"1554035737686"}

**Permissions:** `{"origins":["https://www.bilibili.com/*"],"permissions":["notifications","storage","webRequest","webRequestBlocking"]}`

**Tabs:**

- ID=2 status=complete `https://www.bilibili.com/`

- ID=34 status=complete `https://www.bilibili.com/bangumi/play/ss28296#281206`

- ID=40 status=complete `undefined`

- ID=44 status=loading `undefined`

**Request / Normal XML:** error, status=0 ``

**Request / XML With Param:** error, status=0 ``

**! Exception:** `Uncaught ReferenceError: test_error_log is not defined`

`chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.js` :: 69 :: 1
</details>

**Comment by sushadangchu** [comment]
是我自己的问题，不小心将可读取和更改网站数据设置改了
