### ISSUE TITLE
chrome浏览器突然用不了 错误代码如下

### ISSUE THREAD

**Issue by WLnuo** [xmcp/pakku.js#129]

**Comment by WLnuo** [comment]
网络错误

CID = 7826336

Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://api.bilibili.com/x/v1/dm/list.so?oid=7826336&pakku_request'.

Error: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://api.bilibili.com/x/v1/dm/list.so?oid=7826336&pakku_request'.
    at down_danmaku (chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/all_core.js:1432:13)
    at onbeforerequest (chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/all_core.js:1648:60)
    at subEventCallback (extensions::webRequestEvent:81:32)

**Comment by xmcp** [comment]
网络错误

**Comment by WLnuo** [comment]
如何解决呀，我重新安装还是这样....

**Comment by xmcp** [comment]
不是我的锅，建议检查网络环境。

**Comment by WLnuo** [comment]
是的大佬，网络环境之前正常，未翻墙，我现在尝试翻墙重新安装，翻墙之后重新安装，关闭广告问题解决，可能是之前广告插件拦截了网页相关元素，总而言之谢谢大佬，感谢做出这款很棒的插件！
