### ISSUE TITLE
手动开了 HSTS 后 扩展不工作

### ISSUE THREAD

**Issue by Love4Taylor** [xmcp/pakku.js#20]
网络错误

CID = 19228063

Error: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://comment.bilibili.com/19228063.xml'.
    at load_danmaku (chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/background.js:105:13)
    at chrome.webRequest.onBeforeRequest.addListener.urls (chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/background.js:154:34)
    at subEventCallback (extensions::webRequestEvent:87:32)
    at EventImpl.dispatchToListener (extensions::event_bindings:395:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:149:26)
    at EventImpl.dispatch_ (extensions::event_bindings:379:35)
    at dispatchArgs (extensions::event_bindings:252:26)
    at dispatchEvent (extensions::event_bindings:261:7)

**Comment by fanthos** [comment]
https://github.com/xmcp/pakku.js/blob/master/pakkujs/core/background.js#L102
大概应该把http改成https吧，那样应该就正常了

我觉得更好的解决办法是在
https://github.com/xmcp/pakku.js/blob/master/pakkujs/core/background.js#L147
这一行判断是不是https，如果是的话就在load_danmaku函数里载入https
